//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:05 PM EST 
//


package org.hl7.greencda.c32;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

public class Codes
{
	public Codes()
	{
		
	}

	
	@SerializedName("RxNorm")
    protected List<String> RxNorm =new ArrayList<String>();

	public List<String> getRxNorm() {
		return RxNorm;
	}

	public void setRxNorm(List<String> rxNorm) {
		RxNorm = rxNorm;
	}


	@SerializedName("SNOMED-CT")
    protected List<String> SNOMED_CT =new ArrayList<String>();

	public List<String> getSNOMED_CT() {
		return SNOMED_CT;
	}

	public void setSNOMED_CT(List<String> sNOMED_CT) {
		SNOMED_CT = sNOMED_CT;
	}

	protected List<String>  LOINC= new ArrayList<String>();

	@SerializedName("ICD-9-CM")
    protected List<String> ICD_9_CM = new ArrayList<String>();
    
	protected List<String> HCPCS = new ArrayList<String>();
	
	protected List<String>  CPT = new ArrayList<String>();
	
	public List<String> getICD_9_CM() {
		return ICD_9_CM;
	}

	public void setICD_9_CM(List<String> iCD_9_CM) {
		ICD_9_CM = iCD_9_CM;
	}

	public List<String> getHCPCS() {
		return HCPCS;
	}

	public void setHCPCS(List<String> hCPCS) {
		HCPCS = hCPCS;
	}

	public List<String> getCPT() {
		return CPT;
	}

	public void setCPT(List<String> cPT) {
		CPT = cPT;
	}

	

	public List<String> getLOINC() {
		return LOINC;
	}

	public void setLOINC(List<String> lOINC) {
		LOINC = lOINC;
	}

}
