//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:00 PM EST 
//


package org.hl7.greencda.c32;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for guarantor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="guarantor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="financialResponsibilityDateRange" type="{urn:hl7-org:greencda:c32}interval"/>
 *         &lt;choice>
 *           &lt;element name="organization" type="{urn:hl7-org:greencda:c32}organization"/>
 *           &lt;element name="person" type="{urn:hl7-org:greencda:c32}person"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "guarantor", propOrder = {
    "financialResponsibilityDateRange",
    "organization",
    "person"
})
public class Guarantor {

    @XmlElement(required = true)
    protected Interval financialResponsibilityDateRange;
    protected Organization organization;
    protected Person person;

    /**
     * Gets the value of the financialResponsibilityDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link Interval }
     *     
     */
    public Interval getFinancialResponsibilityDateRange() {
        return financialResponsibilityDateRange;
    }

    /**
     * Sets the value of the financialResponsibilityDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interval }
     *     
     */
    public void setFinancialResponsibilityDateRange(Interval value) {
        this.financialResponsibilityDateRange = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

}
