//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:01 PM EST 
//


package org.hl7.greencda.c32;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:greencda:c32}entry">
 *       &lt;sequence>
 *         &lt;element name="seriesNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="refusalReason" type="{urn:hl7-org:greencda:c32}code"/>
 *       &lt;/sequence>
 *       &lt;attribute name="refused" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seriesNumber",
    "refusalReason"
})
@XmlRootElement(name = "immunization")
public class Immunization
    extends Entry
{

    @XmlElement(required = true)
    protected BigInteger seriesNumber;
    @XmlElement(required = true)
    protected Code refusalReason;
    @XmlAttribute
    protected Boolean refused;

    /**
     * Gets the value of the seriesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * Sets the value of the seriesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeriesNumber(BigInteger value) {
        this.seriesNumber = value;
    }

    /**
     * Gets the value of the refusalReason property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getRefusalReason() {
        return refusalReason;
    }

    /**
     * Sets the value of the refusalReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setRefusalReason(Code value) {
        this.refusalReason = value;
    }

    /**
     * Gets the value of the refused property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefused() {
        return refused;
    }

    /**
     * Sets the value of the refused property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefused(Boolean value) {
        this.refused = value;
    }

}
