//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:00 PM EST 
//


package org.hl7.greencda.c32;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="insuranceType" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="payer" type="{urn:hl7-org:greencda:c32}organization"/>
 *         &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subscriber" type="{urn:hl7-org:greencda:c32}person"/>
 *         &lt;element name="relationshipToSubscriber" type="{urn:hl7-org:greencda:c32}code"/>
 *         &lt;element name="financialResponsibilityType" type="{urn:hl7-org:greencda:c32}code"/>
 *         &lt;element name="guarantor" type="{urn:hl7-org:greencda:c32}guarantor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="healthPlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="freeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "insuranceType",
    "payer",
    "memberID",
    "subscriber",
    "relationshipToSubscriber",
    "financialResponsibilityType",
    "guarantor",
    "healthPlanName",
    "freeText"
})
@XmlRootElement(name = "insuranceProvider")
public class InsuranceProvider {

    @XmlElement(required = true)
    protected String id;
    protected Code insuranceType;
    @XmlElement(required = true)
    protected Organization payer;
    @XmlElement(required = true)
    protected String memberID;
    @XmlElement(required = true)
    protected Person subscriber;
    @XmlElement(required = true)
    protected Code relationshipToSubscriber;
    @XmlElement(required = true)
    protected Code financialResponsibilityType;
    protected List<Guarantor> guarantor;
    @XmlElement(required = true)
    protected String healthPlanName;
    @XmlElement(required = true)
    protected String freeText;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the insuranceType property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getInsuranceType() {
        return insuranceType;
    }

    /**
     * Sets the value of the insuranceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setInsuranceType(Code value) {
        this.insuranceType = value;
    }

    /**
     * Gets the value of the payer property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getPayer() {
        return payer;
    }

    /**
     * Sets the value of the payer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setPayer(Organization value) {
        this.payer = value;
    }

    /**
     * Gets the value of the memberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberID() {
        return memberID;
    }

    /**
     * Sets the value of the memberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberID(String value) {
        this.memberID = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setSubscriber(Person value) {
        this.subscriber = value;
    }

    /**
     * Gets the value of the relationshipToSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getRelationshipToSubscriber() {
        return relationshipToSubscriber;
    }

    /**
     * Sets the value of the relationshipToSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setRelationshipToSubscriber(Code value) {
        this.relationshipToSubscriber = value;
    }

    /**
     * Gets the value of the financialResponsibilityType property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getFinancialResponsibilityType() {
        return financialResponsibilityType;
    }

    /**
     * Sets the value of the financialResponsibilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setFinancialResponsibilityType(Code value) {
        this.financialResponsibilityType = value;
    }

    /**
     * Gets the value of the guarantor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guarantor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuarantor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Guarantor }
     * 
     * 
     */
    public List<Guarantor> getGuarantor() {
        if (guarantor == null) {
            guarantor = new ArrayList<Guarantor>();
        }
        return this.guarantor;
    }

    /**
     * Gets the value of the healthPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthPlanName() {
        return healthPlanName;
    }

    /**
     * Sets the value of the healthPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthPlanName(String value) {
        this.healthPlanName = value;
    }

    /**
     * Gets the value of the freeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeText() {
        return freeText;
    }

    /**
     * Sets the value of the freeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeText(String value) {
        this.freeText = value;
    }

}
