//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:00 PM EST 
//


package org.hl7.greencda.c32;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:greencda:c32}entry">
 *       &lt;sequence>
 *         &lt;element name="administrationTiming">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="period" type="{urn:hl7-org:greencda:c32}quantity"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="institutionSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="route" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="dose" type="{urn:hl7-org:greencda:c32}quantity" minOccurs="0"/>
 *         &lt;element name="doseIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="site" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="doseRestriction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numerator" type="{urn:hl7-org:greencda:c32}quantity"/>
 *                   &lt;element name="denominator" type="{urn:hl7-org:greencda:c32}quantity"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="productForm" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="deliveryMethod" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="type" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="statusOfMedication" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="indication" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="vehicle" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *         &lt;element name="patientInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fulfillmentInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fulfillmentHistory" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="prescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="dispenseDate" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
 *                   &lt;element name="quantityDispensed" type="{urn:hl7-org:greencda:c32}quantity" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fillStatus">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="completed"/>
 *                       &lt;enumeration value="aborted"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="orderInformation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="quantityOrdered" type="{urn:hl7-org:greencda:c32}quantity" minOccurs="0"/>
 *                   &lt;element name="orderedDateTime" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
 *                   &lt;element name="expirationDateTime" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fills" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "administrationTiming",
    "route",
    "dose",
    "doseIndicator",
    "site",
    "doseRestriction",
    "productForm",
    "deliveryMethod",
    "type",
    "statusOfMedication",
    "indication",
    "vehicle",
    "patientInstructions",
    "fulfillmentInstructions",
    "fulfillmentHistory",
    "orderInformation"
})
@XmlRootElement(name = "medication")
public class Medication
    extends Entry
{

    @XmlElement(required = true)
    protected Medication.AdministrationTiming administrationTiming;
    protected Code route;
    protected Quantity dose;
    protected String doseIndicator;
    protected Code site;
    protected Medication.DoseRestriction doseRestriction;
    protected Code productForm;
    protected Code deliveryMethod;
    protected Code type;
    protected Code statusOfMedication;
    protected Code indication;
    protected Code vehicle;
    protected String patientInstructions;
    protected String fulfillmentInstructions;
    protected List<Medication.FulfillmentHistory> fulfillmentHistory;
    protected List<Medication.OrderInformation> orderInformation;

    /**
     * Gets the value of the administrationTiming property.
     * 
     * @return
     *     possible object is
     *     {@link Medication.AdministrationTiming }
     *     
     */
    public Medication.AdministrationTiming getAdministrationTiming() {
        return administrationTiming;
    }

    /**
     * Sets the value of the administrationTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medication.AdministrationTiming }
     *     
     */
    public void setAdministrationTiming(Medication.AdministrationTiming value) {
        this.administrationTiming = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setRoute(Code value) {
        this.route = value;
    }

    /**
     * Gets the value of the dose property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getDose() {
        return dose;
    }

    /**
     * Sets the value of the dose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setDose(Quantity value) {
        this.dose = value;
    }

    /**
     * Gets the value of the doseIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoseIndicator() {
        return doseIndicator;
    }

    /**
     * Sets the value of the doseIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoseIndicator(String value) {
        this.doseIndicator = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setSite(Code value) {
        this.site = value;
    }

    /**
     * Gets the value of the doseRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Medication.DoseRestriction }
     *     
     */
    public Medication.DoseRestriction getDoseRestriction() {
        return doseRestriction;
    }

    /**
     * Sets the value of the doseRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medication.DoseRestriction }
     *     
     */
    public void setDoseRestriction(Medication.DoseRestriction value) {
        this.doseRestriction = value;
    }

    /**
     * Gets the value of the productForm property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getProductForm() {
        return productForm;
    }

    /**
     * Sets the value of the productForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setProductForm(Code value) {
        this.productForm = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setDeliveryMethod(Code value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setType(Code value) {
        this.type = value;
    }

    /**
     * Gets the value of the statusOfMedication property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getStatusOfMedication() {
        return statusOfMedication;
    }

    /**
     * Sets the value of the statusOfMedication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setStatusOfMedication(Code value) {
        this.statusOfMedication = value;
    }

    /**
     * Gets the value of the indication property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getIndication() {
        return indication;
    }

    /**
     * Sets the value of the indication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setIndication(Code value) {
        this.indication = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setVehicle(Code value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the patientInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientInstructions() {
        return patientInstructions;
    }

    /**
     * Sets the value of the patientInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientInstructions(String value) {
        this.patientInstructions = value;
    }

    /**
     * Gets the value of the fulfillmentInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentInstructions() {
        return fulfillmentInstructions;
    }

    /**
     * Sets the value of the fulfillmentInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentInstructions(String value) {
        this.fulfillmentInstructions = value;
    }

    /**
     * Gets the value of the fulfillmentHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fulfillmentHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFulfillmentHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Medication.FulfillmentHistory }
     * 
     * 
     */
    public List<Medication.FulfillmentHistory> getFulfillmentHistory() {
        if (fulfillmentHistory == null) {
            fulfillmentHistory = new ArrayList<Medication.FulfillmentHistory>();
        }
        return this.fulfillmentHistory;
    }

    /**
     * Gets the value of the orderInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Medication.OrderInformation }
     * 
     * 
     */
    public List<Medication.OrderInformation> getOrderInformation() {
        if (orderInformation == null) {
            orderInformation = new ArrayList<Medication.OrderInformation>();
        }
        return this.orderInformation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="period" type="{urn:hl7-org:greencda:c32}quantity"/>
     *       &lt;/sequence>
     *       &lt;attribute name="institutionSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "period"
    })
    public static class AdministrationTiming {

        @XmlElement(required = true)
        protected Quantity period;
        @XmlAttribute
        protected Boolean institutionSpecified;

        /**
         * Gets the value of the period property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setPeriod(Quantity value) {
            this.period = value;
        }

        /**
         * Gets the value of the institutionSpecified property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isInstitutionSpecified() {
            return institutionSpecified;
        }

        /**
         * Sets the value of the institutionSpecified property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setInstitutionSpecified(Boolean value) {
            this.institutionSpecified = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numerator" type="{urn:hl7-org:greencda:c32}quantity"/>
     *         &lt;element name="denominator" type="{urn:hl7-org:greencda:c32}quantity"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numerator",
        "denominator"
    })
    public static class DoseRestriction {

        @XmlElement(required = true)
        protected Quantity numerator;
        @XmlElement(required = true)
        protected Quantity denominator;

        /**
         * Gets the value of the numerator property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getNumerator() {
            return numerator;
        }

        /**
         * Sets the value of the numerator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setNumerator(Quantity value) {
            this.numerator = value;
        }

        /**
         * Gets the value of the denominator property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getDenominator() {
            return denominator;
        }

        /**
         * Sets the value of the denominator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setDenominator(Quantity value) {
            this.denominator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="prescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="dispenseDate" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
     *         &lt;element name="quantityDispensed" type="{urn:hl7-org:greencda:c32}quantity" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="fillStatus">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="completed"/>
     *             &lt;enumeration value="aborted"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prescriptionNumber",
        "dispenseDate",
        "quantityDispensed"
    })
    public static class FulfillmentHistory {

        protected String prescriptionNumber;
        protected Timestamp dispenseDate;
        protected Quantity quantityDispensed;
        @XmlAttribute
        protected String fillStatus;

        /**
         * Gets the value of the prescriptionNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrescriptionNumber() {
            return prescriptionNumber;
        }

        /**
         * Sets the value of the prescriptionNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrescriptionNumber(String value) {
            this.prescriptionNumber = value;
        }

        /**
         * Gets the value of the dispenseDate property.
         * 
         * @return
         *     possible object is
         *     {@link Timestamp }
         *     
         */
        public Timestamp getDispenseDate() {
            return dispenseDate;
        }

        /**
         * Sets the value of the dispenseDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Timestamp }
         *     
         */
        public void setDispenseDate(Timestamp value) {
            this.dispenseDate = value;
        }

        /**
         * Gets the value of the quantityDispensed property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getQuantityDispensed() {
            return quantityDispensed;
        }

        /**
         * Sets the value of the quantityDispensed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setQuantityDispensed(Quantity value) {
            this.quantityDispensed = value;
        }

        /**
         * Gets the value of the fillStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFillStatus() {
            return fillStatus;
        }

        /**
         * Sets the value of the fillStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFillStatus(String value) {
            this.fillStatus = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="quantityOrdered" type="{urn:hl7-org:greencda:c32}quantity" minOccurs="0"/>
     *         &lt;element name="orderedDateTime" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
     *         &lt;element name="expirationDateTime" type="{urn:hl7-org:greencda:c32}timestamp" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fills" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quantityOrdered",
        "orderedDateTime",
        "expirationDateTime"
    })
    public static class OrderInformation {

        protected Quantity quantityOrdered;
        protected Timestamp orderedDateTime;
        protected Timestamp expirationDateTime;
        @XmlAttribute
        protected String orderNumber;
        @XmlAttribute
        protected BigInteger fills;

        /**
         * Gets the value of the quantityOrdered property.
         * 
         * @return
         *     possible object is
         *     {@link Quantity }
         *     
         */
        public Quantity getQuantityOrdered() {
            return quantityOrdered;
        }

        /**
         * Sets the value of the quantityOrdered property.
         * 
         * @param value
         *     allowed object is
         *     {@link Quantity }
         *     
         */
        public void setQuantityOrdered(Quantity value) {
            this.quantityOrdered = value;
        }

        /**
         * Gets the value of the orderedDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link Timestamp }
         *     
         */
        public Timestamp getOrderedDateTime() {
            return orderedDateTime;
        }

        /**
         * Sets the value of the orderedDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Timestamp }
         *     
         */
        public void setOrderedDateTime(Timestamp value) {
            this.orderedDateTime = value;
        }

        /**
         * Gets the value of the expirationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link Timestamp }
         *     
         */
        public Timestamp getExpirationDateTime() {
            return expirationDateTime;
        }

        /**
         * Sets the value of the expirationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Timestamp }
         *     
         */
        public void setExpirationDateTime(Timestamp value) {
            this.expirationDateTime = value;
        }

        /**
         * Gets the value of the orderNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderNumber() {
            return orderNumber;
        }

        /**
         * Sets the value of the orderNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderNumber(String value) {
            this.orderNumber = value;
        }

        /**
         * Gets the value of the fills property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFills() {
            return fills;
        }

        /**
         * Sets the value of the fills property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFills(BigInteger value) {
            this.fills = value;
        }

    }

}
