//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 04:05:00 PM EST 
//


package org.hl7.greencda.c32;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patientInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:hl7-org:greencda:c32}person">
 *                 &lt;sequence>
 *                   &lt;element name="gender" type="{urn:hl7-org:greencda:c32}code"/>
 *                   &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="dateOfDeath" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="maritalStatus" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *                   &lt;element name="religiousAffiliation" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *                   &lt;element name="race" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *                   &lt;element name="ethnicity" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
 *                   &lt;element name="languagesSpoken" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allergies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}allergy" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conditions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}condition" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="immunizations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}immunization" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="insuranceProviders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}insuranceProvider" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="medicalEquipment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}medicalEquipment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="medications">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}medication" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="procedures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}procedure" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}result" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="socialHistory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}socialHistory" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="support">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}support" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vitalSigns">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:hl7-org:greencda:c32}vitalSign" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientInformation",
    "allergies",
    "conditions",
    "immunizations",
    "insuranceProviders",
    "medicalEquipment",
    "medications",
    "procedures",
    "results",
    "socialHistory",
    "support",
    "vitalSigns"
})
@XmlRootElement(name = "record")
public class Record {

    @XmlElement(required = true)
    protected Record.PatientInformation patientInformation;
    @XmlElement(required = true)
    protected Record.Allergies allergies;
    @XmlElement(required = true)
    protected Record.Conditions conditions;
    @XmlElement(required = true)
    protected Record.Immunizations immunizations;
    @XmlElement(required = true)
    protected Record.InsuranceProviders insuranceProviders;
    @XmlElement(required = true)
    protected Record.MedicalEquipment medicalEquipment;
    @XmlElement(required = true)
    protected Record.Medications medications;
    @XmlElement(required = true)
    protected Record.Procedures procedures;
    @XmlElement(required = true)
    protected Record.Results results;
    @XmlElement(required = true)
    protected Record.SocialHistory socialHistory;
    @XmlElement(required = true)
    protected Record.Support support;
    @XmlElement(required = true)
    protected Record.VitalSigns vitalSigns;

    /**
     * Gets the value of the patientInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Record.PatientInformation }
     *     
     */
    public Record.PatientInformation getPatientInformation() {
        return patientInformation;
    }

    /**
     * Sets the value of the patientInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.PatientInformation }
     *     
     */
    public void setPatientInformation(Record.PatientInformation value) {
        this.patientInformation = value;
    }

    /**
     * Gets the value of the allergies property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Allergies }
     *     
     */
    public Record.Allergies getAllergies() {
        return allergies;
    }

    /**
     * Sets the value of the allergies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Allergies }
     *     
     */
    public void setAllergies(Record.Allergies value) {
        this.allergies = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Conditions }
     *     
     */
    public Record.Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Conditions }
     *     
     */
    public void setConditions(Record.Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the immunizations property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Immunizations }
     *     
     */
    public Record.Immunizations getImmunizations() {
        return immunizations;
    }

    /**
     * Sets the value of the immunizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Immunizations }
     *     
     */
    public void setImmunizations(Record.Immunizations value) {
        this.immunizations = value;
    }

    /**
     * Gets the value of the insuranceProviders property.
     * 
     * @return
     *     possible object is
     *     {@link Record.InsuranceProviders }
     *     
     */
    public Record.InsuranceProviders getInsuranceProviders() {
        return insuranceProviders;
    }

    /**
     * Sets the value of the insuranceProviders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.InsuranceProviders }
     *     
     */
    public void setInsuranceProviders(Record.InsuranceProviders value) {
        this.insuranceProviders = value;
    }

    /**
     * Gets the value of the medicalEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link Record.MedicalEquipment }
     *     
     */
    public Record.MedicalEquipment getMedicalEquipment() {
        return medicalEquipment;
    }

    /**
     * Sets the value of the medicalEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.MedicalEquipment }
     *     
     */
    public void setMedicalEquipment(Record.MedicalEquipment value) {
        this.medicalEquipment = value;
    }

    /**
     * Gets the value of the medications property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Medications }
     *     
     */
    public Record.Medications getMedications() {
        return medications;
    }

    /**
     * Sets the value of the medications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Medications }
     *     
     */
    public void setMedications(Record.Medications value) {
        this.medications = value;
    }

    /**
     * Gets the value of the procedures property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Procedures }
     *     
     */
    public Record.Procedures getProcedures() {
        return procedures;
    }

    /**
     * Sets the value of the procedures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Procedures }
     *     
     */
    public void setProcedures(Record.Procedures value) {
        this.procedures = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Results }
     *     
     */
    public Record.Results getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Results }
     *     
     */
    public void setResults(Record.Results value) {
        this.results = value;
    }

    /**
     * Gets the value of the socialHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Record.SocialHistory }
     *     
     */
    public Record.SocialHistory getSocialHistory() {
        return socialHistory;
    }

    /**
     * Sets the value of the socialHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.SocialHistory }
     *     
     */
    public void setSocialHistory(Record.SocialHistory value) {
        this.socialHistory = value;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link Record.Support }
     *     
     */
    public Record.Support getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.Support }
     *     
     */
    public void setSupport(Record.Support value) {
        this.support = value;
    }

    /**
     * Gets the value of the vitalSigns property.
     * 
     * @return
     *     possible object is
     *     {@link Record.VitalSigns }
     *     
     */
    public Record.VitalSigns getVitalSigns() {
        return vitalSigns;
    }

    /**
     * Sets the value of the vitalSigns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record.VitalSigns }
     *     
     */
    public void setVitalSigns(Record.VitalSigns value) {
        this.vitalSigns = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}allergy" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allergy"
    })
    public static class Allergies {

        protected List<Allergy> allergy;

        /**
         * Gets the value of the allergy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the allergy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAllergy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Allergy }
         * 
         * 
         */
        public List<Allergy> getAllergy() {
            if (allergy == null) {
                allergy = new ArrayList<Allergy>();
            }
            return this.allergy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}condition" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "condition"
    })
    public static class Conditions {

        protected List<Condition> condition;

        /**
         * Gets the value of the condition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the condition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCondition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Condition }
         * 
         * 
         */
        public List<Condition> getCondition() {
            if (condition == null) {
                condition = new ArrayList<Condition>();
            }
            return this.condition;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}immunization" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "immunization"
    })
    public static class Immunizations {

        protected List<Immunization> immunization;

        /**
         * Gets the value of the immunization property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the immunization property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImmunization().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Immunization }
         * 
         * 
         */
        public List<Immunization> getImmunization() {
            if (immunization == null) {
                immunization = new ArrayList<Immunization>();
            }
            return this.immunization;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}insuranceProvider" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "insuranceProvider"
    })
    public static class InsuranceProviders {

        protected List<InsuranceProvider> insuranceProvider;

        /**
         * Gets the value of the insuranceProvider property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the insuranceProvider property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInsuranceProvider().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InsuranceProvider }
         * 
         * 
         */
        public List<InsuranceProvider> getInsuranceProvider() {
            if (insuranceProvider == null) {
                insuranceProvider = new ArrayList<InsuranceProvider>();
            }
            return this.insuranceProvider;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}medicalEquipment" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medicalEquipment"
    })
    public static class MedicalEquipment {

        protected List<org.hl7.greencda.c32.MedicalEquipment> medicalEquipment;

        /**
         * Gets the value of the medicalEquipment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the medicalEquipment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMedicalEquipment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link org.hl7.greencda.c32.MedicalEquipment }
         * 
         * 
         */
        public List<org.hl7.greencda.c32.MedicalEquipment> getMedicalEquipment() {
            if (medicalEquipment == null) {
                medicalEquipment = new ArrayList<org.hl7.greencda.c32.MedicalEquipment>();
            }
            return this.medicalEquipment;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}medication" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medication"
    })
    public static class Medications {

        protected List<Medication> medication;

        /**
         * Gets the value of the medication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the medication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMedication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Medication }
         * 
         * 
         */
        public List<Medication> getMedication() {
            if (medication == null) {
                medication = new ArrayList<Medication>();
            }
            return this.medication;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:hl7-org:greencda:c32}person">
     *       &lt;sequence>
     *         &lt;element name="gender" type="{urn:hl7-org:greencda:c32}code"/>
     *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="dateOfDeath" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="maritalStatus" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
     *         &lt;element name="religiousAffiliation" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
     *         &lt;element name="race" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
     *         &lt;element name="ethnicity" type="{urn:hl7-org:greencda:c32}code" minOccurs="0"/>
     *         &lt;element name="languagesSpoken" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gender",
        "dateOfBirth",
        "dateOfDeath",
        "maritalStatus",
        "religiousAffiliation",
        "race",
        "ethnicity",
        "languagesSpoken"
    })
    public static class PatientInformation
        extends Person
    {

        @XmlElement(required = true)
        protected Code gender;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateOfBirth;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateOfDeath;
        protected Code maritalStatus;
        protected Code religiousAffiliation;
        protected Code race;
        protected Code ethnicity;
        protected Record.PatientInformation.LanguagesSpoken languagesSpoken;

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link Code }
         *     
         */
        public Code getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link Code }
         *     
         */
        public void setGender(Code value) {
            this.gender = value;
        }

        /**
         * Gets the value of the dateOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateOfBirth(XMLGregorianCalendar value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the dateOfDeath property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateOfDeath() {
            return dateOfDeath;
        }

        /**
         * Sets the value of the dateOfDeath property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateOfDeath(XMLGregorianCalendar value) {
            this.dateOfDeath = value;
        }

        /**
         * Gets the value of the maritalStatus property.
         * 
         * @return
         *     possible object is
         *     {@link Code }
         *     
         */
        public Code getMaritalStatus() {
            return maritalStatus;
        }

        /**
         * Sets the value of the maritalStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link Code }
         *     
         */
        public void setMaritalStatus(Code value) {
            this.maritalStatus = value;
        }

        /**
         * Gets the value of the religiousAffiliation property.
         * 
         * @return
         *     possible object is
         *     {@link Code }
         *     
         */
        public Code getReligiousAffiliation() {
            return religiousAffiliation;
        }

        /**
         * Sets the value of the religiousAffiliation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Code }
         *     
         */
        public void setReligiousAffiliation(Code value) {
            this.religiousAffiliation = value;
        }

        /**
         * Gets the value of the race property.
         * 
         * @return
         *     possible object is
         *     {@link Code }
         *     
         */
        public Code getRace() {
            return race;
        }

        /**
         * Sets the value of the race property.
         * 
         * @param value
         *     allowed object is
         *     {@link Code }
         *     
         */
        public void setRace(Code value) {
            this.race = value;
        }

        /**
         * Gets the value of the ethnicity property.
         * 
         * @return
         *     possible object is
         *     {@link Code }
         *     
         */
        public Code getEthnicity() {
            return ethnicity;
        }

        /**
         * Sets the value of the ethnicity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Code }
         *     
         */
        public void setEthnicity(Code value) {
            this.ethnicity = value;
        }

        /**
         * Gets the value of the languagesSpoken property.
         * 
         * @return
         *     possible object is
         *     {@link Record.PatientInformation.LanguagesSpoken }
         *     
         */
        public Record.PatientInformation.LanguagesSpoken getLanguagesSpoken() {
            return languagesSpoken;
        }

        /**
         * Sets the value of the languagesSpoken property.
         * 
         * @param value
         *     allowed object is
         *     {@link Record.PatientInformation.LanguagesSpoken }
         *     
         */
        public void setLanguagesSpoken(Record.PatientInformation.LanguagesSpoken value) {
            this.languagesSpoken = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "language"
        })
        public static class LanguagesSpoken {

            @XmlElement(required = true)
            protected List<String> language;

            /**
             * Gets the value of the language property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the language property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLanguage().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getLanguage() {
                if (language == null) {
                    language = new ArrayList<String>();
                }
                return this.language;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}procedure" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "procedure"
    })
    public static class Procedures {

        protected List<Procedure> procedure;

        /**
         * Gets the value of the procedure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the procedure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcedure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Procedure }
         * 
         * 
         */
        public List<Procedure> getProcedure() {
            if (procedure == null) {
                procedure = new ArrayList<Procedure>();
            }
            return this.procedure;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}result" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class Results {

        protected List<Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Result }
         * 
         * 
         */
        public List<Result> getResult() {
            if (result == null) {
                result = new ArrayList<Result>();
            }
            return this.result;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}socialHistory" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "socialHistory"
    })
    public static class SocialHistory {

        protected List<org.hl7.greencda.c32.SocialHistory> socialHistory;

        /**
         * Gets the value of the socialHistory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the socialHistory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSocialHistory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link org.hl7.greencda.c32.SocialHistory }
         * 
         * 
         */
        public List<org.hl7.greencda.c32.SocialHistory> getSocialHistory() {
            if (socialHistory == null) {
                socialHistory = new ArrayList<org.hl7.greencda.c32.SocialHistory>();
            }
            return this.socialHistory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}support" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "support"
    })
    public static class Support {

        protected List<org.hl7.greencda.c32.Support> support;

        /**
         * Gets the value of the support property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the support property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSupport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link org.hl7.greencda.c32.Support }
         * 
         * 
         */
        public List<org.hl7.greencda.c32.Support> getSupport() {
            if (support == null) {
                support = new ArrayList<org.hl7.greencda.c32.Support>();
            }
            return this.support;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:hl7-org:greencda:c32}vitalSign" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vitalSign"
    })
    public static class VitalSigns {

        protected List<Result> vitalSign;

        /**
         * Gets the value of the vitalSign property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vitalSign property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVitalSign().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Result }
         * 
         * 
         */
        public List<Result> getVitalSign() {
            if (vitalSign == null) {
                vitalSign = new ArrayList<Result>();
            }
            return this.vitalSign;
        }

    }

}
