//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.01 at 09:26:28 AM EDT 
//


package org.mitre.medj.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderRxHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderRxHistoryType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:astm-org:CCR}CCRCodedDataObjectType">
 *       &lt;sequence>
 *         &lt;element name="FulfillmentMethod" type="{urn:astm-org:CCR}CodedDescriptionType" minOccurs="0"/>
 *         &lt;element name="Provider" type="{urn:astm-org:CCR}ActorReferenceType" minOccurs="0"/>
 *         &lt;element name="Location" type="{urn:astm-org:CCR}ActorReferenceType" minOccurs="0"/>
 *         &lt;element ref="{urn:astm-org:CCR}Reaction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductName" type="{urn:astm-org:CCR}CodedDescriptionType" minOccurs="0"/>
 *         &lt;element name="BrandName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Manufacturer" type="{urn:astm-org:CCR}ActorReferenceType" minOccurs="0"/>
 *         &lt;element name="IDs" type="{urn:astm-org:CCR}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Strength" type="{urn:astm-org:CCR}MeasureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Form" type="{urn:astm-org:CCR}CodedDescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Concentration" type="{urn:astm-org:CCR}MeasureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{urn:astm-org:CCR}MeasureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LabelInstructions" type="{urn:astm-org:CCR}InstructionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SeriesNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderRxHistoryType", propOrder = {
    "fulfillmentMethod",
    "provider",
    "location",
    "reaction",
    "productName",
    "brandName",
    "manufacturer",
    "orderRxID",
    "strength",
    "form",
    "concentration",
    "quantity",
    "labelInstructions",
    "seriesNumber"
})
public class OrderRxHistoryType
    extends CCRCodedDataObjectType
{

    @XmlElement(name = "FulfillmentMethod")
    protected CodedDescriptionType fulfillmentMethod;
    @XmlElement(name = "Provider")
    protected ActorReferenceType provider;
    @XmlElement(name = "Location")
    protected ActorReferenceType location;
    @XmlElement(name = "Reaction")
    protected List<Reaction> reaction;
    @XmlElement(name = "ProductName")
    protected CodedDescriptionType productName;
    @XmlElement(name = "BrandName")
    protected String brandName;
    @XmlElement(name = "Manufacturer")
    protected ActorReferenceType manufacturer;
    @XmlElement(name = "IDs")
    protected List<IDType> orderRxID;
    @XmlElement(name = "Strength")
    protected List<MeasureType> strength;
    @XmlElement(name = "Form")
    protected List<CodedDescriptionType> form;
    @XmlElement(name = "Concentration")
    protected List<MeasureType> concentration;
    @XmlElement(name = "Quantity")
    protected List<MeasureType> quantity;
    @XmlElement(name = "LabelInstructions")
    protected List<InstructionType> labelInstructions;
    @XmlElement(name = "SeriesNumber")
    protected String seriesNumber;

    /**
     * Gets the value of the fulfillmentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CodedDescriptionType }
     *     
     */
    public CodedDescriptionType getFulfillmentMethod() {
        return fulfillmentMethod;
    }

    /**
     * Sets the value of the fulfillmentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedDescriptionType }
     *     
     */
    public void setFulfillmentMethod(CodedDescriptionType value) {
        this.fulfillmentMethod = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link ActorReferenceType }
     *     
     */
    public ActorReferenceType getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorReferenceType }
     *     
     */
    public void setProvider(ActorReferenceType value) {
        this.provider = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link ActorReferenceType }
     *     
     */
    public ActorReferenceType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorReferenceType }
     *     
     */
    public void setLocation(ActorReferenceType value) {
        this.location = value;
    }

    /**
     * Gets the value of the reaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reaction }
     * 
     * 
     */
    public List<Reaction> getReaction() {
        if (reaction == null) {
            reaction = new ArrayList<Reaction>();
        }
        return this.reaction;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link CodedDescriptionType }
     *     
     */
    public CodedDescriptionType getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedDescriptionType }
     *     
     */
    public void setProductName(CodedDescriptionType value) {
        this.productName = value;
    }

    /**
     * Gets the value of the brandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * Sets the value of the brandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrandName(String value) {
        this.brandName = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link ActorReferenceType }
     *     
     */
    public ActorReferenceType getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorReferenceType }
     *     
     */
    public void setManufacturer(ActorReferenceType value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the orderRxID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderRxID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderRxID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getOrderRxID() {
        if (orderRxID == null) {
            orderRxID = new ArrayList<IDType>();
        }
        return this.orderRxID;
    }

    /**
     * Gets the value of the strength property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strength property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrength().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureType }
     * 
     * 
     */
    public List<MeasureType> getStrength() {
        if (strength == null) {
            strength = new ArrayList<MeasureType>();
        }
        return this.strength;
    }

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedDescriptionType }
     * 
     * 
     */
    public List<CodedDescriptionType> getForm() {
        if (form == null) {
            form = new ArrayList<CodedDescriptionType>();
        }
        return this.form;
    }

    /**
     * Gets the value of the concentration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the concentration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConcentration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureType }
     * 
     * 
     */
    public List<MeasureType> getConcentration() {
        if (concentration == null) {
            concentration = new ArrayList<MeasureType>();
        }
        return this.concentration;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeasureType }
     * 
     * 
     */
    public List<MeasureType> getQuantity() {
        if (quantity == null) {
            quantity = new ArrayList<MeasureType>();
        }
        return this.quantity;
    }

    /**
     * Gets the value of the labelInstructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelInstructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstructionType }
     * 
     * 
     */
    public List<InstructionType> getLabelInstructions() {
        if (labelInstructions == null) {
            labelInstructions = new ArrayList<InstructionType>();
        }
        return this.labelInstructions;
    }

    /**
     * Gets the value of the seriesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * Sets the value of the seriesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesNumber(String value) {
        this.seriesNumber = value;
    }

}
