MSCBFM; MSC/JDA - RPC for FileMan requests ; 02 Feb, 2010
 ;;1.0;MSCFM;;May 14, 2009
ENTRY(RETVAL,ARGBYTES)
 ; Entry point for RPC that handles FileMan requests
 ;  both parameters are in byte format
 N RES,REPLYRES S RES="",REPLYRES="",RETVAL=""
 D FROMBYTE^MSCRES(.RES,.ARGBYTES)
 D PROCESS^MSCFM(.REPLYRES,.RES)
 D TOGLOBAL^MSCRES(.RETVAL,.REPLYRES)
 D DISPOSE^MSCRES(.RES),DISPOSE^MSCRES(.REPLYRES)
 Q
